name: Auto-Merge PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  label-and-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Add 'automerge' label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.CITYBIKEDATARETRIEVALAGENT_GITHUB_TOKEN }}
          labels: automerge

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.CITYBIKEDATARETRIEVALAGENT_GITHUB_TOKEN }}
          merge-method: squash
