name: Dummy Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy status check
        run: echo "This is a dummy status check"
